# Generated by Django 4.2.5 on 2023-09-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ticker", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("shares", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fees", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
