# Generated by Django 4.2.5 on 2023-09-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_stocktransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSpy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("adjusted_close_price", models.FloatField()),
                ("volume", models.BigIntegerField()),
            ],
        ),
    ]
