# Generated by Django 4.2.5 on 2023-09-21 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_dataspy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataSpy",
        ),
    ]
