# Generated by Django 4.2.5 on 2023-09-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_delete_dataspy"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSpy",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("adjusted_close_price", models.FloatField()),
                ("volume", models.BigIntegerField()),
            ],
            options={
                "db_table": "data_spy",
            },
        ),
    ]
