# Generated by Django 4.2.3 on 2023-09-09 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="owner",
        ),
    ]
