# Generated by Django 4.2.5 on 2023-09-09 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_remove_transaction_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transaction",
            new_name="Stocks",
        ),
    ]
